### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by gfred** [quittle/gradle-svg-2-android-vector#177]
Since some updates ago, this library does not work anymore, because the API for `parseSvgToXml` has changed.
From `java.lang.String com.android.ide.common.vectordrawable.Svg2Vector.parseSvgToXml(java.io.File, java.io.OutputStream)`
to `java.lang.String com.android.ide.common.vectordrawable.Svg2Vector.parseSvgToXml(java.nio.file.Path, java.io.OutputStream)`

Would be cool to get this updated :) 
Thank you!

**Comment by quittle** [comment]
I've got a fix but am hitting some other issues as I'm upgrading a bunch of deps at the same time

**Comment by quittle** [comment]
This should now be fixed in version `0.1.0` of the plugin

**Comment by quittle** [comment]
@gfred Could you please try out the new version and confirmed it resolved your issue?

**Comment by gfred** [comment]
@quittle First I must apologize for my late response. I had some time off after I raised this issue and forgot to check back. Sorry.

Just checked today the update and the fix works as expected. 
Thank you very much!
